language: node_js
node_js:
  - '0.10'
install: npm install
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-javascript-sdk-boilerplate' ]; then cd .. && eval "mv $currentfolder generator-javascript-sdk-boilerplate" && cd generator-javascript-sdk-boilerplate; fi

